services:
  - type: worker
    name: traderoom-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python traderoom_bot/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
